services:
  - type: web
    name: swiftboard-api
    env: node
    plan: free
    buildCommand: npm install -g pnpm && pnpm install && npx prisma db push --accept-data-loss && npx prisma generate && pnpm run build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 372086918113-fmdchcpblii6l22k4g2unjkma9g0l28r.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://swiftboard-api.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://swiftboard.devharsh.in
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_USERNAME
        value: harshdipashah@gmail.com
      - key: EMAIL_PASSWORD
        sync: false
      - key: REDIS_URL
        value: redis://red-cvlvba3e5dus73add510:6379
      - key: REDIS_HOST
        value: red-cvlvba3e5dus73add510
      - key: REDIS_PORT
        value: 6379
      - key: AWS_REGION
        value: ap-south-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        value: swiftboard-app
      - key: DATABASE_URL
        fromDatabase:
          name: swiftboard-db
          property: connectionString

databases:
  - name: swiftboard-db
    databaseName: swiftboard
    user: swiftboard_user
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all traffic